# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-17 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0003_numplateresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadmedia',
            name='image_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
