# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-19 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0006_numplateresult_result_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadmedia',
            name='image_id',
        ),
        migrations.AddField(
            model_name='numplateresult',
            name='image_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
