# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-19 17:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0007_auto_20180719_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='numplateresult',
            old_name='result_id',
            new_name='result',
        ),
    ]
