# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-02 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='password',
            field=models.CharField(blank=True, default=b'', max_length=10),
        ),
    ]
